
watch:
    cargo watch --workdir /workspace/ \
      -w crates/web-server \
      -w crates/web-pages \
      -w crates/clorinde \
      -w crates/web-assets/dist \
      --no-gitignore \
      -x "run --bin web-server"